#!/bin/sh

. /usr/local/lib/cont-init-functions.sh
ENSURE_DIR_MODE=2755
ENSURE_DIR_USER=jutut
ENSURE_DIR_GROUP=nogroup

ensure_dir /run/jutut
ensure_dir /local/jutut
ensure_dir /local/jutut/static
ensure_dir /local/jutut/media
